# Image to be updated to include CI for iOS when possible
image: reactnativecommunity/react-native-android

before_script:
  - npm install

stages:
  - lint

eslint:
  stage: lint
  script: 
    - npx eslint .