pool:
  vmImage: ubuntu-latest

# container: reactnativecommunity/react-native-android:latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x.x'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    npm install

- script: npx eslint .
  displayName: 'Lint'
