pool:
  vmImage: ubuntu-latest

trigger: none

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x.x'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    NPM_TOKEN=$(System.AccessToken) yarn install

- script: NPM_TOKEN=$(System.AccessToken) yarn lint
  displayName: 'Lint'
