pool:
  vmImage: ubuntu-latest

trigger: none

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x.x'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    ! grep -i "uat.numberless.tech" src/configs/api.ts
  displayName: 'Ensure not UAT'

- script: |
    NPM_TOKEN=$(System.AccessToken) yarn install
  displayName: 'Install dependencies'

- script: NPM_TOKEN=$(System.AccessToken) yarn lint
  displayName: 'Lint'
