pool:
  vmImage: ubuntu-latest

# container: reactnativecommunity/react-native-android:latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x.x'

- script: |
    NPM_TOKEN=$(NPM_TOKEN) npm install
  displayName: 'Install Node dependencies'

- script: npx eslint .
  displayName: 'Lint'
