name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'refs/pull/*/head'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  validate-cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Not on UAT
        run: |
          ! grep -i "uat.numberless.tech" src/configs/api.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install

      - name: Lint with eslint
        run: yarn lint
